name: Build and Test

# This workflow is triggered on pushes and pull requests to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Jobs to be run
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Sets up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Specify the Python version

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy

    # Run tests or other commands
    - name: Run script
      run: |
        python main.py # Replace with your test command or script
