name: Build and Test Kivy App

# این workflow در هنگام push یا pull request به شاخه اصلی فعال می‌شود
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # راه‌اندازی محیط پایتون
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.18'

    # نصب وابستگی‌ها
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy

    # اجرای اسکریپت تست یا دیگر دستورات
    - name: Run script
      run: |
        python main.py # یا هر دستور دیگری برای تست یا اجرای برنامه شما
