name: Build and Test Kivy App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy

    # Run the script using xvfb-run
    - name: Run script with xvfb
      run: |
        sudo apt-get install -y xvfb
        xvfb-run -s "-screen 0 1024x768x24" python main.py
